// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilesCarRental.Infraestructure.Data.Context;

#nullable disable

namespace MilesCarRental.Infraestructure.Data.Migrations
{
    [DbContext(typeof(VehiculosMilesCarDbContext))]
    [Migration("20240224200357_InitalMigration")]
    partial class InitalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MilesCarRental.Domain.Models.Localidad", b =>
                {
                    b.Property<int>("IdLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLocalidad");

                    b.ToTable("Localidad");
                });

            modelBuilder.Entity("MilesCarRental.Domain.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdVehiculo");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("MilesCarRental.Domain.Models.VehiculoLocalidad", b =>
                {
                    b.Property<int>("VehiculoLocalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LocalidadEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("LocalidadRecogidaId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("VehiculoLocalidadId");

                    b.HasIndex("LocalidadEntregaId");

                    b.HasIndex("LocalidadRecogidaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("VehiculoLocalidad");
                });

            modelBuilder.Entity("MilesCarRental.Domain.Models.VehiculoLocalidad", b =>
                {
                    b.HasOne("MilesCarRental.Domain.Models.Localidad", "LocalidadEntrega")
                        .WithMany("VehiculoLocalidadesEntrega")
                        .HasForeignKey("LocalidadEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilesCarRental.Domain.Models.Localidad", "LocalidadRecogida")
                        .WithMany("VehiculoLocalidadesRecogida")
                        .HasForeignKey("LocalidadRecogidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilesCarRental.Domain.Models.Vehiculo", "Vehiculo")
                        .WithMany("VehiculoLocalidades")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalidadEntrega");

                    b.Navigation("LocalidadRecogida");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MilesCarRental.Domain.Models.Localidad", b =>
                {
                    b.Navigation("VehiculoLocalidadesEntrega");

                    b.Navigation("VehiculoLocalidadesRecogida");
                });

            modelBuilder.Entity("MilesCarRental.Domain.Models.Vehiculo", b =>
                {
                    b.Navigation("VehiculoLocalidades");
                });
#pragma warning restore 612, 618
        }
    }
}
